### ISSUE TITLE
Can't import OPML file exported from Feedly

### ISSUE THREAD

**Issue by kissrichard** [hello-efficiency-inc/raven-reader#491]
**Describe the bug**
I've tried to import my feeds, but the operation gets stuck at the end (?) of the import process.

**To Reproduce**
Go to https://feedly.com/i/opml
Click on "Download your Feedly OPML"
Open Raven
Click on Import Subscriptions

**Expected behaviour**
Because OPML is a standard file format that's why the app can read it without any issues.

**Screenshots**
<img width="887" alt="raven_import_bug" src="https://user-images.githubusercontent.com/16692627/97536921-347cb200-19be-11eb-8780-2109f56069bc.png">

**Desktop:**
 - Windows 10 Enterprise / 1909 / 18363.1016

**My OPML file (!!! extension changed to txt !!!):**
[FEEDLY_BACKUP.txt](https://github.com/hello-efficiency-inc/raven-reader/files/5456687/FEEDLY_BACKUP.txt)

**Comment by mrgodhani** [comment]
It is because one of the RSS Feed link not working http://www.rollingstone.com/music.rss. Will investigate and fix error handling on next release

**Comment by kissrichard** [comment]
THX!

**Comment by mrgodhani** [comment]
Fixed in 1.0.11

**Comment by sanawu** [comment]
I have this problem also, this is quite a normal scenario when links can fail

**Comment by mrgodhani** [comment]
@sanawu what's your opml file?

**Comment by sanawu** [comment]
I tried importing in FeedReader, it works, Raven hangs

**Comment by sanawu** [comment]
This is NOT fixed in 1.0.12 AppImage

Hand picked errors from render.log

[2020-10-31 08:39:33.663] [info] Error: Too many redirects
    at ClientRequest.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810430)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)

[2020-10-31 08:39:33.450] [info] Error: Invalid character in tag name
Line: 2
Column: 411
Char: ;
    at z (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:418839)
    at k (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:419215)
    at i.write (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:409204)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:836479)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:831057)
    at /tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809380
    at new Promise (<anonymous>)
    at e.exports.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809345)
    at IncomingMessage.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810740)
    at IncomingMessage.emit (events.js:322:22)

[2020-10-31 08:39:31.860] [info] Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 
    at z (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:418839)
    at k (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:419215)
    at W (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:422669)
    at i.write (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:405487)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:836479)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:831057)
    at /tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809380
    at new Promise (<anonymous>)
    at e.exports.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809345)
    at IncomingMessage.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810740)


[2020-10-31 08:39:31.674] [info] Error: Status code 404
    at ClientRequest.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810578)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)

[2020-10-31 08:39:31.611] [info] Error: Invalid character in entity name
Line: 6
Column: 346
Char: &
    at z (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:418839)
    at k (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:419215)
    at i.write (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:411930)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:836479)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:831057)
    at /tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809380
    at new Promise (<anonymous>)
    at e.exports.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809345)
    at IncomingMessage.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810740)
    at IncomingMessage.emit (events.js:322:22)

[2020-10-31 08:39:30.413] [info] Error: Unexpected close tag
Line: 51
Column: 9
Char: >
    at z (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:418839)
    at k (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:419215)
    at q (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:421647)
    at i.write (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:411078)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:836479)
    at i.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:831057)
    at /tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809380
    at new Promise (<anonymous>)
    at e.exports.parseString (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:809345)
    at IncomingMessage.<anonymous> (/tmp/.mount_Raven aURUZG/resources/app.asar/preload.js:2:810740)


[2020-10-31 08:39:30.681] [info] Error: getaddrinfo ENOTFOUND <DOMAIN REDACTED>
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)

**Comment by sanawu** [comment]
May I suggest considering using a file fuzzer for generating OPML files and running those through and files with unreachable, and high redirecting links in order to get some rhobustness into your importer code

**Comment by sanawu** [comment]
May I also suggest having it preview the import (including showing unreachable and failed parses) and then we can see from the tree which ones are unreachable, and hand pick feeds or groups of feeds to finalise into the import

**Comment by mrgodhani** [comment]
I can right now already import OPML from feedly from the previous issue.  That's the reason I asked what is your opml file and upload it here to further debug.

**Comment by sanawu** [comment]
Let me strip down the OPML to get a minimal reproducable, you won't be getting the full OPML as it has personal identifying information in it

**Comment by timmyreal** [comment]
I'm having the exact same problem.
