### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure

### ISSUE THREAD

**Issue by dflock** [hello-efficiency-inc/raven-reader#565]
**Describe the bug**

I get the following error in the console on startup.

**To Reproduce**
1. Run: `Raven-Reader-1.0.54_3c36340c8f608f8705d1256ff8e52e28.AppImage --no-sandbox --trace-warnings %U`
2. Watch console output:

```
➜ /home/duncan/Applications/Raven-Reader-1.0.54_3c36340c8f608f8705d1256ff8e52e28.AppImage --no-sandbox --trace-warnings %U
qt5ct: using qt5ct plugin
(electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure
21:17:55.711 › Checking for update
21:17:55.713 › Checking for update...
21:17:55.896 › Language changed
21:17:55.903 › Language changed
(node:573232) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from 
    at Dn.enable (/tmp/.mount_Raven-EU996k/resources/app.asar/background.js:2:839428)
    at Object.enableBlockingInSession (/tmp/.mount_Raven-EU996k/resources/app.asar/background.js:2:904070)
    at /tmp/.mount_Raven-EU996k/resources/app.asar/background.js:2:904416
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `raven-reader --trace-warnings ...` to show where the warning was created)
(node:573232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:573232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
21:17:56.854 › Update for version 1.0.54 is not available (latest version: 1.0.54, downgrade is disallowed).
21:17:56.855 › Update not available.
21:17:56.856 › checkForUpdatesAndNotify called, downloadPromise is null
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04

**Comment by mrgodhani** [comment]
This should be fixed as well in the latest.
